/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * This class is the Initial Frame of the App
 * show 3 buttons for each replacement algorithm and a jcomboBox for select the
 * page number
 * @author joshu
 */
public class MenuInicial extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicial
     */
    public MenuInicial() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbLRU = new javax.swing.JButton();
        jbFIFO = new javax.swing.JButton();
        jbRELOJ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jcNumPages = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jbLRU.setText("LRU");
        jbLRU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLRUActionPerformed(evt);
            }
        });

        jbFIFO.setText("FIFO");
        jbFIFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFIFOActionPerformed(evt);
            }
        });

        jbRELOJ.setText("RELOJ");
        jbRELOJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRELOJActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione uno de los siguientes algoritmos");

        jcNumPages.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9", "10", "11", "12", "13", "14", "15", "16" }));
        jcNumPages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcNumPagesActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccione la cantidad de paginas para el algoritmo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbLRU)
                        .addGap(43, 43, 43)
                        .addComponent(jbFIFO)
                        .addGap(32, 32, 32)
                        .addComponent(jbRELOJ))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jcNumPages, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLRU)
                    .addComponent(jbFIFO)
                    .addComponent(jbRELOJ)
                    .addComponent(jcNumPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method create the LRU page with the require pages number
     *
     * @param evt
     */
    private void jbLRUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLRUActionPerformed
        int paginas = Integer.parseInt(jcNumPages.getSelectedItem().toString());
        VistaLRU LRU;
        try {
            LRU = new VistaLRU(this, true, paginas);
            LRU.setVisible(true);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);

    }//GEN-LAST:event_jbLRUActionPerformed
    
    /**
     * This method create the FIFO page with the require pages number
     *
     * @param evt
     */
    private void jbFIFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFIFOActionPerformed
       int paginas = Integer.parseInt(jcNumPages.getSelectedItem().toString());
        VistaFIFO FIFO;
        try {
            FIFO = new VistaFIFO(this, true, paginas);
            FIFO.setVisible(true);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_jbFIFOActionPerformed

    /**
     * This method create the Reloj page with the require pages number
     *
     * @param evt
     */
    private void jbRELOJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRELOJActionPerformed
        int paginas = Integer.parseInt(jcNumPages.getSelectedItem().toString());
        VistaRELOJ reloj;
        try {
            reloj = new VistaRELOJ(this, true, paginas);
            reloj.setVisible(true);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_jbRELOJActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jcNumPagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcNumPagesActionPerformed

    }//GEN-LAST:event_jcNumPagesActionPerformed

    /**
     * This method validate the number of pages entered by the user
     * @return the validate number of pages
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbFIFO;
    private javax.swing.JButton jbLRU;
    private javax.swing.JButton jbRELOJ;
    private javax.swing.JComboBox<String> jcNumPages;
    // End of variables declaration//GEN-END:variables
}
